services:
  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php${PHP_VERSION:-8.4}-apache
    container_name: wp_app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wp:/var/www/html

  wpcli:
    image: wordpress:cli
    container_name: wp_cli
    depends_on:
      - db
      - wordpress
    volumes:
      - ./wp:/var/www/html
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
