services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wp-instant:latest
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    container_name: ${PROJECT_NAME}_app
    ports:
      - "${WP_PORT}:80"
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}

  wpcli:
    image: wp-instant:latest
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    container_name: ${PROJECT_NAME}_cli
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html
      - ./plugins-private:/plugins-private
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
